USE cctv_booking;

ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS email VARCHAR(160) NOT NULL AFTER phone,
  ADD COLUMN IF NOT EXISTS service_address TEXT NOT NULL AFTER email,
  ADD COLUMN IF NOT EXISTS service_type ENUM('New CCTV Installation', 'Repair', 'Maintenance', 'Camera Upgrade') NOT NULL DEFAULT 'New CCTV Installation' AFTER service_address,
  ADD COLUMN IF NOT EXISTS preferred_date DATE NULL AFTER cameras,
  ADD COLUMN IF NOT EXISTS preferred_time TIME NULL AFTER preferred_date,
  ADD COLUMN IF NOT EXISTS message TEXT NULL AFTER preferred_time,
  ADD COLUMN IF NOT EXISTS status ENUM('Pending', 'Confirmed', 'Completed', 'Cancelled') NOT NULL DEFAULT 'Pending' AFTER message,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER status,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

ALTER TABLE maintenance_requests
  ADD COLUMN IF NOT EXISTS status ENUM('Pending', 'Confirmed', 'Completed', 'Cancelled') NOT NULL DEFAULT 'Pending',
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE contacts
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
